print("Welcome to the Band Name Generator.")
city_name = input("What's the name of the city you grew up in?\n")
pet_name = input("What is your pet's name?\n")
# print("Your name could be", city_name + " " + pet_name)
print(f"Your name could be {city_name}  {pet_name}")